### ISSUE TITLE
Issues related to CKAN and DLL name

### ISSUE THREAD

**Issue by JonnyOThan** [alobazombie/kOS-Ferram#3]
![image](https://github.com/giuliodondi/kOS-Ferram/assets/9804078/71313ef0-a109-47ba-ab02-6abe8710d19c)

CKAN assumes that a mod named `something.*.dll` is the DLL associated with `something` and the `*` is the version name (as in modulemanager).  This causes issues where CKAN thinks kos.addons.ferram.dll is the kos dll but installed in the wrong place.  Presumably also if you had kos-ferram installed without kos then it would think kos itself is installed.

It seems pretty unlikely that CKAN's logic for this will change, but if this mod ever gets updated could you please rename the DLL?  And we'd love to have it on CKAN as well - I can help with that, just let me know!

**Comment by giuliodondi** [comment]
Sure, shouldn't be hard.
Could you give me the steps to replicate the problem you see? So I can make sure I pick a name that will not cause it anymore.

Also yeah, I never really put any thought about releasing this for CKAN but if this makes it more reachable to people I'd like to see it there

**Comment by JonnyOThan** [comment]
Oh I was just informed that if we add this to CKAN the problem will go away anyway.  I can do that for you if you like!
