### ISSUE TITLE
KSPAssemblyDependency declares a dependency on KOS 1.4, but the current version is marked 1.3

### ISSUE THREAD

**Issue by JonnyOThan** [alobazombie/kOS-Ferram#4]
details here: https://github.com/KSP-CKAN/NetKAN/pull/9858#issuecomment-1823801870

**Comment by giuliodondi** [comment]
This might be the problem that I encountered the first time I renamed the .dll, which I didn't recognize as such at first.
It was already fixed in the source code but the release I created was not up-to-date.

It is now and I verified the plugin works with kOS 1.4.0
