### ISSUE TITLE
Fetching FAR's aerotorque vector gives the same output as aeroforce

### ISSUE THREAD

**Issue by Kerburettor** [alobazombie/kOS-Ferram#5]
Hi Giulio,

It's a quick fix but I noticed that `addons:far:aerotorque.` and `addons:far:aeroforce.` produce the exact same result, which is probably due to a typo at line 188 of FARWrapper.cs:
Instead of 

`public static Vector3? GetFARAeroTorque()
        {
            return (Vector3?)FARAeroforce.Invoke(null, new object[] { });
        }`

there should be

`public static Vector3? GetFARAeroTorque()
        {
            return (Vector3?)FARAerotorque.Invoke(null, new object[] { });
        }
`
instead.
Is it possible to check if you encounter the same issue?

Cheers

**Comment by giuliodondi** [comment]
should be fixed now, thanks !

Edit: would you know how to report to the CKAN lot that a new version has been rolled out and that the metadata should be updated to point to it?
